CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    CREATE TABLE "Todos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "IsCompleted" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAt" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "Priority" character varying(50) NOT NULL DEFAULT 'Medium',
        "Category" character varying(100),
        CONSTRAINT "PK_Todos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    INSERT INTO "Todos" ("Id", "Category", "CompletedAt", "CreatedAt", "Description", "Priority", "Title", "UpdatedAt")
    VALUES (1, 'Development', NULL, TIMESTAMPTZ '2025-07-14T16:52:39.785646Z', 'Set up the initial .NET API project with Entity Framework and PostgreSQL', 'High', 'Complete project setup', NULL);
    INSERT INTO "Todos" ("Id", "Category", "CompletedAt", "CreatedAt", "Description", "Priority", "Title", "UpdatedAt")
    VALUES (2, 'Development', NULL, TIMESTAMPTZ '2025-07-14T16:52:39.785676Z', 'Create endpoints for Create, Read, Update, and Delete operations for todos', 'High', 'Implement CRUD operations', NULL);
    INSERT INTO "Todos" ("Id", "Category", "CompletedAt", "CreatedAt", "Description", "Priority", "Title", "UpdatedAt")
    VALUES (3, 'DevOps', NULL, TIMESTAMPTZ '2025-07-14T16:52:39.785676Z', 'Configure GitHub Actions for continuous integration and deployment', 'Medium', 'Set up CI/CD pipeline', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    CREATE INDEX "IX_Todos_CreatedAt" ON "Todos" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    CREATE INDEX "IX_Todos_IsCompleted" ON "Todos" ("IsCompleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    CREATE INDEX "IX_Todos_Priority" ON "Todos" ("Priority");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Todos"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Todos") + 1,
            nextval(pg_get_serial_sequence('"Todos"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714165240_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250714165240_InitialCreate', '9.0.7');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714170528_FixSeedDataWithStaticDates') THEN
    UPDATE "Todos" SET "CreatedAt" = TIMESTAMPTZ '2024-01-15T10:00:00Z'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714170528_FixSeedDataWithStaticDates') THEN
    UPDATE "Todos" SET "CreatedAt" = TIMESTAMPTZ '2024-01-15T10:05:00Z'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714170528_FixSeedDataWithStaticDates') THEN
    UPDATE "Todos" SET "CreatedAt" = TIMESTAMPTZ '2024-01-15T10:10:00Z'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250714170528_FixSeedDataWithStaticDates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250714170528_FixSeedDataWithStaticDates', '9.0.7');
    END IF;
END $EF$;
COMMIT;

